export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';

export const SET_ACTIVE_FEATURE = 'SET_ACTIVE_FEATURE';

export const SET_ACTIVE_CROP_OPTION = 'SET_ACTIVE_CROP_OPTION';
export const SET_CROP_PARAMS = 'SET_CROP_PARAMS';
export const CROP_IMAGE = 'CROP_IMAGE';

export const SET_RESIZE = 'SET_REIZE';

export const SET_DRAG = 'SET_DRAG';

export const SET_ZOOM = 'SET_ZOOM';

export const SET_FLIP = 'SET_FLIP';
export const FLIP_IMAGE = 'FLIP_IMAGE';

export const SET_DEGREE = 'SET_DEGREE';
export const ROTATE_IMAGE = 'ROTATE_IMAGE';

export const SET_BRIGHTNESS = 'SET_BRIGHTNESS';
export const SET_CONTRAST = 'SET_CONTRAST';
export const SET_SATURATION = 'SET_SATURATION';
export const SET_SHARPNESS = 'SET_SHARPNESS';
export const SET_BLUR = 'SET_BLUR';
export const BASIC_ADJUST_IMAGE = 'BASIC_ADJUST_IMAGE';

export const SET_TEMPERATURE = 'SET_TEMPERATURE';
export const SET_TINT = 'SET_TINT';
export const COLOR_IMAGE = 'COLOR_IMAGE';

export const SET_INVERT = 'SET_INVERT';
export const INVERT_IMAGE = 'INVERT_IMAGE';

export const SET_EFFECT = 'SET_EFFECT';
export const EFFECT_IMAGE = 'EFFECT_IMAGE';

export const SET_SCENE_EFFECT = 'SET_SCENE_EFFECT';
export const SCENE_IMAGE = 'SCENE_IMAGE';

export const SET_CLASSIC_EFFECT = 'SET_CLASSIC_EFFECT';
export const CLASSIC_IMAGE = 'CLASSIC_IMAGE';

export const SET_RETRO_EFFECT = 'SET_RETRO_EFFECT';
export const RETRO_IMAGE = 'RETRO_IMAGE';

export const SET_LAYOUT = 'SET_LAYOUT';
export const SET_LAYOUT_DIMENSION = 'SET_LAYOUT_DIMENSION';
export const SET_LAYOUT_BORDER = 'SET_LAYOUT_BORDER';
export const SET_LAYOUT_COLOR = 'SET_LAYOUT_COLOR';
export const LAYOUT_IMAGE = 'LAYOUT_IMAGE';