export const IMAGE_UPLOAD_SUCCESS = 'IMAGE_UPLOAD_SUCCESS';
export const IMAGE_UPLOAD_FAILURE = 'IMAGE_UPLOAD_FAILURE';

export const SET_ACTIVE_FEATURE = 'SET_ACTIVE_FEATURE';

export const SET_ACTIVE_CROP_OPTION = 'SET_ACTIVE_CROP_OPTION';
export const SET_CROP_PARAMS = 'SET_CROP_PARAMS';
export const CROP_IMAGE = 'CROP_IMAGE';

export const SET_RESIZE = 'SET_REIZE';

export const SET_DRAG = 'SET_DRAG';

export const SET_ZOOM = 'SET_ZOOM';